### PR TITLE
various documentation enhancements

### PR DESCRIPTION
**Pull request by vincentfretin**
Specify buttons available in documentation, instead of needing to look at the code.

### CODE REVIEW

**Comment by fernandojsg** [comment]
Thanks @vincentfretin !

**Comment by vincentfretin** [comment]
Thanks for merging it! ;-)
For the slowness, the lag I get, when I show the curved line, I'll try to understand why this is slow in oculus browser with GearVR. Do you have an idea? What is different from the straight line?

For the fact we need to specify gearvr-controls or daydream-controls, we should remove that and include those components in the teleport component, like it's done for look-controls component or progressive-controls component in super-hands package. I'll probably do a new PR for that unless someone else do it before me.

**Comment by fernandojsg** [comment]
With a simple line it just do a raycast, but a curve is composed of several lines so several raycast for each line. There're ways to optimize it, for example create a boundingbox of the curve and check the collision against the rest of geometry and if it doesn't collide don't try to use the raycast as it won't collide either. I'll probably open an issue with suggestions for performance improvement

**Comment by fernandojsg** [comment]
Regarding the gear and daydream controllers, I just got two of them to try but I didn't have the chance yet

**Pull request merged**
